### ISSUE TITLE
Add posibility to install it in python 3.6

### ISSUE THREAD

**Issue by manuoso** [Bardo91/fastcom#3]
Currently only support python3 install that is python 3.5

**Comment by Bardo91** [comment]
Do you have any clue about how to do it? The installation is done by a python script that is called in the custom target "install_python" in the CMakeLists. This is the fille that is called "https://github.com/Bardo91/fastcom/blob/master/python/setup.py". This is the standard way of installing the python files and I am not quite sure how to choose between different Python version packages folder. 

In the CMakeLists, the custom target is configured to use "Python3" as it is. It means that it should use the python version that you have installed. What is the output when you type `python3 --version`?

**Comment by Bardo91** [comment]
Should be solved in https://github.com/Bardo91/fastcom/commit/aa0a851e68a5afd31e43c91c1ddb7df58f5a8885

Nevertheless, it could be better if you set python3.6 to the standard python3 version in your computer.
