### ISSUE TITLE
Link with another program does not work

### ISSUE THREAD

**Issue by manuoso** [Bardo91/fastcom#6]
CMakeFiles/handling_node.dir/src/main.cpp.o:` In function `boost::exception_detail::error_info_injector<boost::system::system_error>::error_info_injector(boost::exception_detail::error_info_injector<boost::system::system_error> const&)':
/usr/local/include/fastcom/impl/StringSubscriber.inl:30: multiple definition of `bool fastcom::Subscriber<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::listenCallback_impl<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
CMakeFiles/handling_node.dir/src/StateMachine.cpp.o:/usr/local/include/fastcom/impl/StringSubscriber.inl:30: first defined here
CMakeFiles/handling_node.dir/src/main.cpp.o: In function `fastcom::Publisher<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::publish(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/local/include/fastcom/impl/StringPublisher.inl:27: multiple definition of `fastcom::Publisher<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::publish(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/handling_node.dir/src/StateMachine.cpp.o:/usr/local/include/fastcom/impl/StringPublisher.inl:27: first defined here
collect2: error: ld returned 1 exit status
tools/handling_node/CMakeFiles/handling_node.dir/build.make:148: recipe for target 'tools/handling_node/handling_node' failed
make[2]: *** [tools/handling_node/handling_node] Error 1
CMakeFiles/Makefile2:171: recipe for target 'tools/handling_node/CMakeFiles/handling_node.dir/all' failed
make[1]: *** [tools/handling_node/CMakeFiles/handling_node.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Bardo91** [comment]
Fixed in commit https://github.com/Bardo91/fastcom/commit/76fad59416060ea7c9b8e3b1082d567659051b6b (a.k.a. v1.4.0)
