### ISSUE TITLE
Redefinition listenCallback_impl and publish.

### ISSUE THREAD

**Issue by Ric92** [Bardo91/fastcom#7]
Happened in: f844c6f0317f7d3503b809483f23c5c299020ed4

1>Module.AirSim.gen.cpp.obj : error LNK2005: "private: bool __cdecl fastcom::Subscriber<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >::listenCallback_impl<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (??$listenCallback_impl@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@?$Subscriber@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@fastcom@@AEAA_NAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) already defined in Module.AirSim.cpp.obj

1>Module.AirSim.gen.cpp.obj : error LNK2005: "public: void __cdecl fastcom::Publisher<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >::publish(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?publish@?$Publisher@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@fastcom@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) already defined in Module.AirSim.cpp.obj

**Comment by Bardo91** [comment]
It seems to be related with https://github.com/Bardo91/fastcom/issues/6

**Comment by Bardo91** [comment]
Could you check if it is solved in commit 76fad59 (a.k.a. v1.4.0) and close the issue if it is

**Comment by Bardo91** [comment]
Deprecared in Fastcom 2.x.x
